spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=cart_service
    username: sa
    password: 123!P01@W
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    com:
      active:
        services:
          cart:
            repository: DEBUG

url:
  orderManagementBase: http://127.0.0.1:8200