spring:
  datasource:
    url: jdbc:sqlserver://DBDEVAW01.dev.activenetwork.com:1433;databaseName=cart_service
    username: cart_service
    password: sb9O1AlbwSjJYTgjPrfn
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    com:
      active:
        services:
          cart:
            repository: DEBUG

url:
  orderManagementBase: http://order-vip.int.aw.dev.activenetwork.com