spring:
  datasource:
    url: jdbc:sqlserver://localhost:1435;databaseName=cart_service
    username: fnd_dev_usr
    password: fnd_dev_usr$2008
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    com:
      active:
        services:
          cart:
            repository: DEBUG
            client:
              rest:
                FeignConfigurator: DEBUG

url:
  orderManagementBase: http://order-vip.pint.aw.dev.activenetwork.com
  inventoryServiceBase: http://inventory-pint-awplatform.aw.k8sw.dev.activenetwork.com
  productServiceBase: http://product-pint-awplatform.aw.k8sw.dev.activenetwork.com
  contractServiceBase: http://contract-pint-awplatform.aw.k8sw.dev.activenetwork.com